version: 2
updates:
  - package-ecosystem: npm
    directory: /angular-client
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "typescript"
          - "zone.js"
      angular-security:
        applies-to: security-updates
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "typescript"
          - "zone.js"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
