version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      browser-tests:
        patterns:
          - "@playwright/*"
          - "playwright*"
      browser-test-security:
        applies-to: security-updates
        patterns:
          - "@playwright/*"
          - "playwright*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
